///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GitTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("b8b618f7-5973-4e11-8746-089625982152", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GitTestRepository repository.
        /// </summary>
        public static GitTestRepository repo = GitTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.ranorex.com' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("http://www.ranorex.com", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=18,Width=46,Height=47}) on item 'AutomatedTestingSoftwareRanorexT.HttpWwwRanorexCom'.", repo.AutomatedTestingSoftwareRanorexT.HttpWwwRanorexComInfo, new RecordItemIndex(1));
            Validate.ContainsImage(repo.AutomatedTestingSoftwareRanorexT.HttpWwwRanorexComInfo, HttpWwwRanorexCom_Screenshot1, HttpWwwRanorexCom_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AutomatedTestingSoftwareRanorexT.DownloadFreeTrial' at 42;31.", repo.AutomatedTestingSoftwareRanorexT.DownloadFreeTrialInfo, new RecordItemIndex(2));
            repo.AutomatedTestingSoftwareRanorexT.DownloadFreeTrial.Click("42;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeTrialRanorexAutomatedSoftwar.Schliessen' at 8;12.", repo.FreeTrialRanorexAutomatedSoftwar.SchliessenInfo, new RecordItemIndex(3));
            repo.FreeTrialRanorexAutomatedSoftwar.Schliessen.Click("8;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage HttpWwwRanorexCom_Screenshot1
        { get { return repo.AutomatedTestingSoftwareRanorexT.HttpWwwRanorexComInfo.GetScreenshot1(new Rectangle(0, 18, 46, 47)); } }

        Imaging.FindOptions HttpWwwRanorexCom_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
